config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/auth', to: 'auth#index'

  resources :notifications, only: [:index] do
    collection do
      post :refresh
    end

    member do
      post :read
      post :reply
    end
  end
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :notifications
end

app/models/card.rb
class Card < ActiveRecord::Base
  has_many :notifications
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :created_notifications,
    class_name: Notification,
    foreign_key: :member_creator_id

  def self.refresh_notification(trello_client, params = { read_filter: :unread })
    # params = {} # for debug
    me = trello_client.find(:members, :me)
    logger.debug "[DEBUG] trello me: #{me.inspect}"

    me.notifications(params).each do |n|
      logger.debug "[DEBUG] trello notification.data: #{n.data}"

      board = Board.find_or_create_by id: n.data['board']['id'] do |b|
        b.short_link = n.data['board']['shortLink']
        b.name = n.data['board']['name']
      end if n.data['board']

      card = Card.find_or_create_by id: n.data['card']['id'] do |c|
        c.short_link = n.data['card']['shortLink']
        c.id_short = n.data['card']['idShort']
        c.name = n.data['card']['name']
      end if n.data['card']

      begin
        Member.find(n.member_creator_id)
      rescue ActiveRecord::RecordNotFound
        # 可优化为 delay 执行
        member = trello_client.find(:members, n.member_creator_id)
        Member.create id: member.id,
          username: member.username,
          email: member.email,
          full_name: member.full_name,
          initials: member.initials,
          avatar_id: member.avatar_id,
          bio: member.bio,
          url: member.url
      end

      Notification.find_or_create_by id: n.id do |nf|
        nf.board = board
        nf.card = card

        nf.mentioned_to = me.id

        nf.unread = n.unread
        nf.nf_type = n.type
        nf.date = n.date
        nf.content = n.data['text']
        nf.member_creator_id = n.member_creator_id
      end
    end
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  MENTIONED_ON_CARD = 'mentionedOnCard'.freeze
  MEMBER_JOINED_TRELLO = 'memberJoinedTrello'.freeze

  belongs_to :board
  belongs_to :card
  belongs_to :creator_member,
    class_name: Member,
    foreign_key: :member_creator_id

  def unread
    self[:unread].to_sym == :t ? true : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def trello_client
    Trello::Client.new(
      developer_public_key: Settings.trello.developer_public_key,
      member_token: session[:member_token]
    )
  end

  def current_user_id
    if session[:current_user_id].nil?
      begin
        session[:current_user_id] = trello_client.find(:members, :me).id
      rescue Trello::Error => e
        session.clear
        redirect_to root_path, alert: "#{e.to_s}, please clear your cookies."
      end
    end
    session[:current_user_id]
  end

  def need_connect_with_trello
    logger.debug "[DEBUG] session member_token: #{session[:member_token]}"

    redirect_to(
      root_path,
      status: 302,
      alert: 'You need connect with Trello.'
    ) if session[:member_token].nil?
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def index
    logger.debug "[DEBUG] auth#index token: #{params[:token]}"

    session[:member_token] = params[:token]
    redirect_to notifications_path, notice: 'login success.'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :need_connect_with_trello

  def index
    @notifications = Notification
      .page(params[:page])
      .includes(:creator_member, :board, :card)
      .where(mentioned_to: current_user_id, nf_type: Notification::MENTIONED_ON_CARD)
      .order(unread: :desc, date: :desc).all
  end

  def read
    notification_id = params[:id]
    unread_state = false

    resp = trello_client.put(
      "/notifications/#{notification_id}",
      unread: unread_state
    )
    logger.debug "[DEBUG] response: #{resp.inspect}"
    unread_state =  JSON.parse(resp)['unread']

    @notification = Notification.find(notification_id)
    @notification.update unread: unread_state
  end

  def reply
    @reply_id = params[:id]
  end

  def refresh
    Member.refresh_notification(trello_client)
    flash[:notice] = 'notification updated.'
    render js: "window.location = '#{notifications_path}'"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/home/index.haml
-#%script{src: "//api.trello.com/1/client.js?key=#{Settings.trello.developer_public_key}"}
:javascript
  function AuthenticateTrello() {
    Trello.authorize({
      name: "xz's Trello",
      type: "popup",
      interactive: true,
      expiration: "never",
      persist: true,
      success: function () { onAuthorizeSuccessful(); },
      error: function() { onFailedAuthorization(); },
      scope: { write: true, read: true, account: true }
    });

    return 0;
  }
  function onAuthorizeSuccessful() {
    var token = Trello.token();
    window.location.replace("/auth?token=" + token);
  }
  function onFailedAuthorization() {
    alert('Authentication failed.');
  }

%a.btn.btn-primary{onClick: "AuthenticateTrello()"}
  Connect With Trello

app/views/layouts/application.html.haml
!!!
%html(lang="zh-CN")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title Trello manager
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    %script{src: "//api.trello.com/1/client.js?key=#{Settings.trello.developer_public_key}"}
    = surround raw("<!--[if lt IE 9]>\n"), raw("\n<![endif]-->") do
      = javascript_include_tag "html5"

    = content_for?(:head) ? yield(:head) : nil
    = csrf_meta_tags

  %body
    .navbar.navbar-default
      .navbar-header
        %a.navbar-brand.logo(href="/")
          Trello Notifications
    .container
      - if notice
        .alert.alert-success=notice
      - if alert
        .alert.alert-danger=alert
      = content_for?(:content) ? yield(:content) : yield

app/views/notifications/index.haml
.notifications
  .actions.clearfix
    = link_to 'refresh from Trello', refresh_notifications_path,
      remote: true, method: :post, id: :refresh_notifications,
      class: %w(btn btn-default pull-right)
  = paginate @notifications
  %ul
    - @notifications.each do |notification|
      %li.notification
        .panel.panel-default
          .panel-heading
            %span.label.label-info.time
              = l notification.date, format: :short
            %span.avatar
              %img{src: "https://trello-avatars.s3.amazonaws.com/#{notification.creator_member.avatar_id}/30.png"}

            / xieyunzi mentioned you on the `card_name` card on `board_name` board
            = link_to notification.creator_member.full_name, notification.creator_member.url
            mentioned you on the card
            = link_to "#{notification.card.name}",
              "https://trello.com/c/#{notification.card.short_link}"
            on
            = link_to "#{notification.board.name}",
              "https://trello.com/b/#{notification.board.short_link}"
            board

            %span.pull-right
              = link_to t("notifications.unread.#{notification.unread}"),
                read_notification_path(notification.id),
                remote: true, method: :post, data: { id: notification.id },
                class: %w(btn btn-default btn-xs), id: "unread-#{notification.id}",
                disabled: !notification.unread
          %div.panel-body
            %p.well.well-sm
              = notification.content
            %hr
            %p.reply-content
              .span.help-block
                You don't need mention him(or her) manually, we do that for you.
              %textarea.form-control{row: 5, id: "reply-content-#{notification.id}"}
            = link_to 'Send', reply_notification_path(notification.id),
              id: "reply-#{notification.id}",
              remote: true, method: :post, class: %w(btn btn-default),
              data: { id: notification.id,
                path: "/cards/#{notification.card.id}/actions/comments",
                creator_member: "@#{notification.creator_member.username}" }
  = paginate @notifications